export const LOAD_RELEASES = 'LOAD_RELEASES';
export const LOAD_RELEASES_COMPLETED = 'LOAD_RELEASES_COMPLETED';
export const OPEN_RELEASE = 'OPEN_RELEASE';
export const CLOSE_RELEASE = 'CLOSE_RELEASE';
export const OPEN_RELEASE_COMPLETED = 'OPEN_RELEASE_COMPLETED';